[versions]

kotlin = "2.4.20"
android-gradle-plugin = "9.4.1"
androidUiTestingUtils = "2.7.0"
roborazzi = "1.75.0"

[libraries]

androidx-ktx = { group = "androidx.core", name = "core-ktx", version = "1.19.1" }

androiduitestingutils-utils = { group = "com.github.sergio-sastre.AndroidUiTestingUtils", name = "utils", version.ref = "androidUiTestingUtils" }
androiduitestingutils-robolectric = { group = "com.github.sergio-sastre.AndroidUiTestingUtils", name = "robolectric", version.ref = "androidUiTestingUtils" }
roboelectric = { group = "org.robolectric", name = "robolectric", version = "4.17" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazzi-junit = { group = "io.github.takahirom.roborazzi", name = "roborazzi-junit-rule", version.ref = "roborazzi" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version = "6.1.3" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "6.1.3" }

[plugins]

android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "14.2.0" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

[bundles]

screenshotTests = ["androiduitestingutils-utils", "androiduitestingutils-robolectric", "roboelectric", "roborazzi", "roborazzi-junit", "junit-vintage-engine", "junit-platform-launcher"]
